# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.box = "yungsang/boot2docker"

    config.vm.network "private_network", ip: "10.10.10.10"
    config.vm.synced_folder "~/Development", "/Development", type: "nfs"
    
    # Fix busybox/udhcpc issue
    config.vm.provision :shell do |s|
        s.inline = <<-EOT
            if ! grep -qs ^nameserver /etc/resolv.conf; then
                sudo /sbin/udhcpc
            fi
            cat /etc/resolv.conf
        EOT
    end

    # Adjust datetime after suspend and resume
    config.vm.provision :shell do |s|
        s.inline = <<-EOT
            sudo /usr/local/bin/ntpclient -s -h pool.ntp.org
            date
        EOT
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 4
    end
end
